[package]
name = "vitruvian-dbs"
version = "0.1.0"
edition = "2021"

# [lib]
# crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
vitruvian-types = { path = "../src-types" }

[dependencies]
clap = {version="4.5.20", features=["cargo"]}
git2 = "0.19.0"
rusqlite = "0.32.1"
sea-query = "0.32.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
spinoff = "0.8.0"
strum = { version = "0.26" }
strum_macros = { version = "0.26" }
